services:
  - type: web
    name: samudradrishti-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000

